# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QFrame,
    QGroupBox, QLabel, QMainWindow, QPushButton,
    QRadioButton, QSizePolicy, QSpinBox, QStatusBar,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QSize(400, 240))
        font = QFont()
        font.setFamilies([u"Bahnschrift"])
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        self.centralwidget.setFont(font)
        self.centralwidget.setAutoFillBackground(False)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1281, 141))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setFamilies([u"Bahnschrift"])
        font1.setPointSize(14)
        self.tabWidget.setFont(font1)
        self.HOME = QWidget()
        self.HOME.setObjectName(u"HOME")
        self.HOME.setEnabled(True)
        self.label_DEM_data = QLabel(self.HOME)
        self.label_DEM_data.setObjectName(u"label_DEM_data")
        self.label_DEM_data.setGeometry(QRect(20, 30, 81, 51))
        self.label_DEM_data.setFont(font1)
        self.btn_load_dem = QPushButton(self.HOME)
        self.btn_load_dem.setObjectName(u"btn_load_dem")
        self.btn_load_dem.setGeometry(QRect(70, 30, 131, 51))
        font2 = QFont()
        font2.setFamilies([u"Bahnschrift Light Condensed"])
        font2.setPointSize(14)
        self.btn_load_dem.setFont(font2)
        self.btn_about = QPushButton(self.HOME)
        self.btn_about.setObjectName(u"btn_about")
        self.btn_about.setGeometry(QRect(980, 30, 150, 50))
        self.btn_about.setFont(font2)
        self.btn_file_format = QPushButton(self.HOME)
        self.btn_file_format.setObjectName(u"btn_file_format")
        self.btn_file_format.setGeometry(QRect(800, 30, 150, 50))
        self.btn_file_format.setFont(font2)
        self.btn_docs = QPushButton(self.HOME)
        self.btn_docs.setObjectName(u"btn_docs")
        self.btn_docs.setGeometry(QRect(620, 30, 150, 50))
        self.btn_docs.setFont(font2)
        self.label_unil_2 = QLabel(self.HOME)
        self.label_unil_2.setObjectName(u"label_unil_2")
        self.label_unil_2.setGeometry(QRect(1170, 40, 61, 31))
        font3 = QFont()
        font3.setFamilies([u"Bahnschrift"])
        font3.setPointSize(18)
        self.label_unil_2.setFont(font3)
        self.groupBox_2 = QGroupBox(self.HOME)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(220, 0, 371, 101))
        self.load_project = QPushButton(self.groupBox_2)
        self.load_project.setObjectName(u"load_project")
        self.load_project.setGeometry(QRect(10, 30, 161, 51))
        self.load_project.setFont(font2)
        self.save_project = QPushButton(self.groupBox_2)
        self.save_project.setObjectName(u"save_project")
        self.save_project.setGeometry(QRect(190, 30, 161, 51))
        self.save_project.setFont(font2)
        self.tabWidget.addTab(self.HOME, "")
        self.FailureSurface = QWidget()
        self.FailureSurface.setObjectName(u"FailureSurface")
        self.groupBox_4 = QGroupBox(self.FailureSurface)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(260, 0, 1011, 111))
        self.btn_save_slbl = QPushButton(self.groupBox_4)
        self.btn_save_slbl.setObjectName(u"btn_save_slbl")
        self.btn_save_slbl.setGeometry(QRect(880, 70, 91, 31))
        font4 = QFont()
        font4.setFamilies([u"Bahnschrift Light Condensed"])
        font4.setPointSize(12)
        self.btn_save_slbl.setFont(font4)
        self.btn_compute_slbl = QPushButton(self.groupBox_4)
        self.btn_compute_slbl.setObjectName(u"btn_compute_slbl")
        self.btn_compute_slbl.setGeometry(QRect(290, 40, 191, 50))
        self.btn_compute_slbl.setFont(font4)
        self.btn_graph_slbl = QPushButton(self.groupBox_4)
        self.btn_graph_slbl.setObjectName(u"btn_graph_slbl")
        self.btn_graph_slbl.setGeometry(QRect(690, 30, 131, 31))
        self.btn_graph_slbl.setFont(font4)
        self.btn_clear_graph_slbl = QPushButton(self.groupBox_4)
        self.btn_clear_graph_slbl.setObjectName(u"btn_clear_graph_slbl")
        self.btn_clear_graph_slbl.setGeometry(QRect(690, 70, 131, 31))
        self.btn_clear_graph_slbl.setFont(font4)
        self.btn_load_slbl = QPushButton(self.groupBox_4)
        self.btn_load_slbl.setObjectName(u"btn_load_slbl")
        self.btn_load_slbl.setGeometry(QRect(30, 40, 191, 51))
        self.btn_load_slbl.setFont(font4)
        self.line_4 = QFrame(self.groupBox_4)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(240, 50, 20, 31))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.slbl_axis = QCheckBox(self.groupBox_4)
        self.slbl_axis.setObjectName(u"slbl_axis")
        self.slbl_axis.setGeometry(QRect(840, 40, 111, 18))
        font5 = QFont()
        font5.setFamilies([u"Bahnschrift"])
        font5.setPointSize(11)
        self.slbl_axis.setFont(font5)
        self.groupBox = QGroupBox(self.FailureSurface)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 0, 231, 111))
        self.slbl1 = QRadioButton(self.groupBox)
        self.slbl1.setObjectName(u"slbl1")
        self.slbl1.setGeometry(QRect(10, 30, 69, 18))
        self.slbl1.setChecked(True)
        self.slbl2 = QRadioButton(self.groupBox)
        self.slbl2.setObjectName(u"slbl2")
        self.slbl2.setGeometry(QRect(10, 60, 69, 18))
        self.slbl3 = QRadioButton(self.groupBox)
        self.slbl3.setObjectName(u"slbl3")
        self.slbl3.setGeometry(QRect(10, 90, 69, 18))
        self.slbl5 = QRadioButton(self.groupBox)
        self.slbl5.setObjectName(u"slbl5")
        self.slbl5.setGeometry(QRect(130, 60, 69, 18))
        self.slbl6 = QRadioButton(self.groupBox)
        self.slbl6.setObjectName(u"slbl6")
        self.slbl6.setGeometry(QRect(130, 90, 69, 18))
        self.slbl4 = QRadioButton(self.groupBox)
        self.slbl4.setObjectName(u"slbl4")
        self.slbl4.setGeometry(QRect(130, 30, 69, 18))
        self.tabWidget.addTab(self.FailureSurface, "")
        self.DISP_VEC = QWidget()
        self.DISP_VEC.setObjectName(u"DISP_VEC")
        self.groupBox_8 = QGroupBox(self.DISP_VEC)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(260, 0, 1011, 111))
        self.btn_clear_graph_disp_vec = QPushButton(self.groupBox_8)
        self.btn_clear_graph_disp_vec.setObjectName(u"btn_clear_graph_disp_vec")
        self.btn_clear_graph_disp_vec.setGeometry(QRect(740, 70, 101, 31))
        self.btn_clear_graph_disp_vec.setFont(font4)
        self.btn_compute_disp_proc = QPushButton(self.groupBox_8)
        self.btn_compute_disp_proc.setObjectName(u"btn_compute_disp_proc")
        self.btn_compute_disp_proc.setGeometry(QRect(520, 40, 191, 50))
        self.btn_compute_disp_proc.setFont(font4)
        self.btn_graph_disp_vec = QPushButton(self.groupBox_8)
        self.btn_graph_disp_vec.setObjectName(u"btn_graph_disp_vec")
        self.btn_graph_disp_vec.setGeometry(QRect(740, 20, 101, 31))
        self.btn_graph_disp_vec.setFont(font4)
        self.btn_save_disp_vec = QPushButton(self.groupBox_8)
        self.btn_save_disp_vec.setObjectName(u"btn_save_disp_vec")
        self.btn_save_disp_vec.setGeometry(QRect(890, 60, 101, 41))
        self.btn_save_disp_vec.setFont(font4)
        self.btn_load_disp_vec = QPushButton(self.groupBox_8)
        self.btn_load_disp_vec.setObjectName(u"btn_load_disp_vec")
        self.btn_load_disp_vec.setGeometry(QRect(880, 20, 121, 31))
        self.btn_load_disp_vec.setFont(font4)
        self.line_5 = QFrame(self.groupBox_8)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(210, 30, 20, 71))
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label = QLabel(self.groupBox_8)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(240, 20, 181, 31))
        self.label.setFont(font5)
        self.spinBox_n = QSpinBox(self.groupBox_8)
        self.spinBox_n.setObjectName(u"spinBox_n")
        self.spinBox_n.setGeometry(QRect(400, 20, 91, 31))
        self.spinBox_n.setFont(font5)
        self.spinBox_n.setMinimum(1)
        self.spinBox_n.setMaximum(999)
        self.spinBox_n.setValue(10)
        self.x_max = QDoubleSpinBox(self.groupBox_8)
        self.x_max.setObjectName(u"x_max")
        self.x_max.setGeometry(QRect(400, 80, 91, 31))
        self.x_max.setFont(font5)
        self.x_max.setDecimals(1)
        self.x_max.setMaximum(50000.000000000000000)
        self.x_max.setValue(500.000000000000000)
        self.label_DEM_data_4 = QLabel(self.groupBox_8)
        self.label_DEM_data_4.setObjectName(u"label_DEM_data_4")
        self.label_DEM_data_4.setGeometry(QRect(270, 80, 121, 41))
        self.label_DEM_data_4.setFont(font5)
        self.label_DEM_data_3 = QLabel(self.groupBox_8)
        self.label_DEM_data_3.setObjectName(u"label_DEM_data_3")
        self.label_DEM_data_3.setGeometry(QRect(270, 50, 121, 41))
        self.label_DEM_data_3.setFont(font5)
        self.x_min = QDoubleSpinBox(self.groupBox_8)
        self.x_min.setObjectName(u"x_min")
        self.x_min.setGeometry(QRect(400, 50, 91, 31))
        self.x_min.setFont(font5)
        self.x_min.setDecimals(1)
        self.x_min.setMaximum(50000.000000000000000)
        self.x_min.setValue(100.000000000000000)
        self.btn_lin_prof = QPushButton(self.groupBox_8)
        self.btn_lin_prof.setObjectName(u"btn_lin_prof")
        self.btn_lin_prof.setGeometry(QRect(0, 20, 211, 41))
        font6 = QFont()
        font6.setFamilies([u"Bahnschrift"])
        font6.setPointSize(12)
        self.btn_lin_prof.setFont(font6)
        self.label_DEM_data_5 = QLabel(self.groupBox_8)
        self.label_DEM_data_5.setObjectName(u"label_DEM_data_5")
        self.label_DEM_data_5.setGeometry(QRect(20, 50, 121, 41))
        self.label_DEM_data_5.setFont(font6)
        self.label_DEM_data_6 = QLabel(self.groupBox_8)
        self.label_DEM_data_6.setObjectName(u"label_DEM_data_6")
        self.label_DEM_data_6.setGeometry(QRect(120, 50, 121, 41))
        self.label_DEM_data_6.setFont(font6)
        self.r_left = QDoubleSpinBox(self.groupBox_8)
        self.r_left.setObjectName(u"r_left")
        self.r_left.setGeometry(QRect(10, 80, 71, 31))
        self.r_left.setFont(font5)
        self.r_left.setAlignment(Qt.AlignCenter)
        self.r_left.setDecimals(1)
        self.r_left.setMaximum(9999.000000000000000)
        self.r_left.setValue(1.000000000000000)
        self.r_right = QDoubleSpinBox(self.groupBox_8)
        self.r_right.setObjectName(u"r_right")
        self.r_right.setGeometry(QRect(110, 80, 71, 31))
        self.r_right.setFont(font5)
        self.r_right.setAlignment(Qt.AlignCenter)
        self.r_right.setDecimals(1)
        self.r_right.setMaximum(9999.000000000000000)
        self.r_right.setValue(1.000000000000000)
        self.vec_axis = QCheckBox(self.groupBox_8)
        self.vec_axis.setObjectName(u"vec_axis")
        self.vec_axis.setGeometry(QRect(760, 50, 101, 18))
        self.vec_axis.setFont(font5)
        self.btn_clear_graph_disp_vec.raise_()
        self.btn_compute_disp_proc.raise_()
        self.btn_graph_disp_vec.raise_()
        self.btn_save_disp_vec.raise_()
        self.btn_load_disp_vec.raise_()
        self.label.raise_()
        self.spinBox_n.raise_()
        self.x_max.raise_()
        self.label_DEM_data_4.raise_()
        self.label_DEM_data_3.raise_()
        self.x_min.raise_()
        self.btn_lin_prof.raise_()
        self.label_DEM_data_5.raise_()
        self.label_DEM_data_6.raise_()
        self.r_left.raise_()
        self.r_right.raise_()
        self.line_5.raise_()
        self.vec_axis.raise_()
        self.groupBox_3 = QGroupBox(self.DISP_VEC)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 0, 231, 111))
        self.dv_slbl1 = QRadioButton(self.groupBox_3)
        self.dv_slbl1.setObjectName(u"dv_slbl1")
        self.dv_slbl1.setGeometry(QRect(10, 30, 69, 18))
        self.dv_slbl1.setChecked(True)
        self.dv_slbl2 = QRadioButton(self.groupBox_3)
        self.dv_slbl2.setObjectName(u"dv_slbl2")
        self.dv_slbl2.setGeometry(QRect(10, 60, 69, 18))
        self.dv_slbl3 = QRadioButton(self.groupBox_3)
        self.dv_slbl3.setObjectName(u"dv_slbl3")
        self.dv_slbl3.setGeometry(QRect(10, 90, 69, 18))
        self.dv_slbl5 = QRadioButton(self.groupBox_3)
        self.dv_slbl5.setObjectName(u"dv_slbl5")
        self.dv_slbl5.setGeometry(QRect(130, 60, 69, 18))
        self.dv_slbl6 = QRadioButton(self.groupBox_3)
        self.dv_slbl6.setObjectName(u"dv_slbl6")
        self.dv_slbl6.setGeometry(QRect(130, 90, 69, 18))
        self.dv_slbl4 = QRadioButton(self.groupBox_3)
        self.dv_slbl4.setObjectName(u"dv_slbl4")
        self.dv_slbl4.setGeometry(QRect(130, 30, 69, 18))
        self.tabWidget.addTab(self.DISP_VEC, "")
        self.COMP_DISP = QWidget()
        self.COMP_DISP.setObjectName(u"COMP_DISP")
        self.groupBox_9 = QGroupBox(self.COMP_DISP)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(260, 0, 1011, 111))
        self.btn_clear_comp_disp = QPushButton(self.groupBox_9)
        self.btn_clear_comp_disp.setObjectName(u"btn_clear_comp_disp")
        self.btn_clear_comp_disp.setGeometry(QRect(890, 25, 101, 31))
        self.btn_clear_comp_disp.setFont(font4)
        self.btn_save_comp_disp = QPushButton(self.groupBox_9)
        self.btn_save_comp_disp.setObjectName(u"btn_save_comp_disp")
        self.btn_save_comp_disp.setGeometry(QRect(890, 60, 101, 41))
        self.btn_save_comp_disp.setFont(font4)
        self.btn_graph_model = QPushButton(self.groupBox_9)
        self.btn_graph_model.setObjectName(u"btn_graph_model")
        self.btn_graph_model.setGeometry(QRect(660, 20, 121, 25))
        self.btn_graph_model.setFont(font4)
        self.btn_load_disp_data = QPushButton(self.groupBox_9)
        self.btn_load_disp_data.setObjectName(u"btn_load_disp_data")
        self.btn_load_disp_data.setGeometry(QRect(20, 40, 171, 41))
        self.btn_load_disp_data.setFont(font4)
        self.line_6 = QFrame(self.groupBox_9)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(420, 50, 20, 31))
        self.line_6.setFrameShape(QFrame.VLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.btn_compute_model = QPushButton(self.groupBox_9)
        self.btn_compute_model.setObjectName(u"btn_compute_model")
        self.btn_compute_model.setGeometry(QRect(460, 40, 191, 51))
        self.btn_compute_model.setFont(font4)
        self.btn_graph_comp = QPushButton(self.groupBox_9)
        self.btn_graph_comp.setObjectName(u"btn_graph_comp")
        self.btn_graph_comp.setGeometry(QRect(660, 50, 121, 25))
        self.btn_graph_comp.setFont(font4)
        self.btn_def_model = QPushButton(self.groupBox_9)
        self.btn_def_model.setObjectName(u"btn_def_model")
        self.btn_def_model.setGeometry(QRect(220, 40, 171, 41))
        self.btn_def_model.setFont(font4)
        self.btn_graph_corr = QPushButton(self.groupBox_9)
        self.btn_graph_corr.setObjectName(u"btn_graph_corr")
        self.btn_graph_corr.setGeometry(QRect(660, 80, 121, 25))
        self.btn_graph_corr.setFont(font4)
        self.model_axis = QCheckBox(self.groupBox_9)
        self.model_axis.setObjectName(u"model_axis")
        self.model_axis.setGeometry(QRect(790, 25, 131, 18))
        self.model_axis.setFont(font5)
        self.groupBox_5 = QGroupBox(self.COMP_DISP)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 0, 231, 111))
        self.dm_slbl1 = QCheckBox(self.groupBox_5)
        self.dm_slbl1.setObjectName(u"dm_slbl1")
        self.dm_slbl1.setGeometry(QRect(10, 30, 58, 18))
        self.dm_slbl1.setChecked(True)
        self.dm_slbl2 = QCheckBox(self.groupBox_5)
        self.dm_slbl2.setObjectName(u"dm_slbl2")
        self.dm_slbl2.setGeometry(QRect(10, 60, 58, 18))
        self.dm_slbl3 = QCheckBox(self.groupBox_5)
        self.dm_slbl3.setObjectName(u"dm_slbl3")
        self.dm_slbl3.setGeometry(QRect(10, 90, 58, 18))
        self.dm_slbl5 = QCheckBox(self.groupBox_5)
        self.dm_slbl5.setObjectName(u"dm_slbl5")
        self.dm_slbl5.setGeometry(QRect(120, 60, 58, 18))
        self.dm_slbl6 = QCheckBox(self.groupBox_5)
        self.dm_slbl6.setObjectName(u"dm_slbl6")
        self.dm_slbl6.setGeometry(QRect(120, 90, 58, 18))
        self.dm_slbl4 = QCheckBox(self.groupBox_5)
        self.dm_slbl4.setObjectName(u"dm_slbl4")
        self.dm_slbl4.setGeometry(QRect(120, 30, 58, 18))
        self.ratio_slbl1 = QDoubleSpinBox(self.groupBox_5)
        self.ratio_slbl1.setObjectName(u"ratio_slbl1")
        self.ratio_slbl1.setGeometry(QRect(40, 30, 62, 22))
        self.ratio_slbl1.setDecimals(1)
        self.ratio_slbl1.setValue(1.000000000000000)
        self.ratio_slbl2 = QDoubleSpinBox(self.groupBox_5)
        self.ratio_slbl2.setObjectName(u"ratio_slbl2")
        self.ratio_slbl2.setGeometry(QRect(40, 60, 62, 22))
        self.ratio_slbl2.setDecimals(1)
        self.ratio_slbl2.setValue(1.000000000000000)
        self.ratio_slbl3 = QDoubleSpinBox(self.groupBox_5)
        self.ratio_slbl3.setObjectName(u"ratio_slbl3")
        self.ratio_slbl3.setGeometry(QRect(40, 90, 62, 22))
        self.ratio_slbl3.setDecimals(1)
        self.ratio_slbl3.setValue(1.000000000000000)
        self.ratio_slbl4 = QDoubleSpinBox(self.groupBox_5)
        self.ratio_slbl4.setObjectName(u"ratio_slbl4")
        self.ratio_slbl4.setGeometry(QRect(160, 30, 62, 22))
        self.ratio_slbl4.setDecimals(1)
        self.ratio_slbl4.setValue(1.000000000000000)
        self.ratio_slbl5 = QDoubleSpinBox(self.groupBox_5)
        self.ratio_slbl5.setObjectName(u"ratio_slbl5")
        self.ratio_slbl5.setGeometry(QRect(160, 60, 62, 22))
        self.ratio_slbl5.setDecimals(1)
        self.ratio_slbl5.setValue(1.000000000000000)
        self.ratio_slbl6 = QDoubleSpinBox(self.groupBox_5)
        self.ratio_slbl6.setObjectName(u"ratio_slbl6")
        self.ratio_slbl6.setGeometry(QRect(160, 90, 62, 22))
        self.ratio_slbl6.setDecimals(1)
        self.ratio_slbl6.setValue(1.000000000000000)
        self.tabWidget.addTab(self.COMP_DISP, "")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 140, 1281, 591))
        sizePolicy1 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy1)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Failure Surface Analysis", None))
        self.label_DEM_data.setText(QCoreApplication.translate("MainWindow", u"DEM", None))
        self.btn_load_dem.setText(QCoreApplication.translate("MainWindow", u"Load DEM", None))
        self.btn_about.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.btn_file_format.setText(QCoreApplication.translate("MainWindow", u"Step-by-step guide", None))
        self.btn_docs.setText(QCoreApplication.translate("MainWindow", u"Read Me", None))
        self.label_unil_2.setText(QCoreApplication.translate("MainWindow", u"UNIL", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Project", None))
        self.load_project.setText(QCoreApplication.translate("MainWindow", u"Load Project", None))
        self.save_project.setText(QCoreApplication.translate("MainWindow", u"Save Project", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HOME), QCoreApplication.translate("MainWindow", u"Home", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Edit Failure Surface", None))
        self.btn_save_slbl.setText(QCoreApplication.translate("MainWindow", u"Save SLBL", None))
        self.btn_compute_slbl.setText(QCoreApplication.translate("MainWindow", u"Compute SLBL Surface", None))
        self.btn_graph_slbl.setText(QCoreApplication.translate("MainWindow", u"Display Failure Surface", None))
        self.btn_clear_graph_slbl.setText(QCoreApplication.translate("MainWindow", u"Clear graph", None))
        self.btn_load_slbl.setText(QCoreApplication.translate("MainWindow", u"Load Failure Surface File", None))
        self.slbl_axis.setText(QCoreApplication.translate("MainWindow", u"Axis 1:1", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Slide Selection", None))
        self.slbl1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.slbl2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.slbl3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.slbl5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.slbl6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.slbl4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FailureSurface), QCoreApplication.translate("MainWindow", u"Failure Surface", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Edit Displacement Vectors", None))
        self.btn_clear_graph_disp_vec.setText(QCoreApplication.translate("MainWindow", u"Clear graph", None))
        self.btn_compute_disp_proc.setText(QCoreApplication.translate("MainWindow", u"Compute displacement vectors", None))
        self.btn_graph_disp_vec.setText(QCoreApplication.translate("MainWindow", u"Display Vectors", None))
        self.btn_save_disp_vec.setText(QCoreApplication.translate("MainWindow", u"Save Vectors", None))
        self.btn_load_disp_vec.setText(QCoreApplication.translate("MainWindow", u"Load Vectors File", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Number of vectors:", None))
        self.x_max.setSuffix(QCoreApplication.translate("MainWindow", u"m", None))
        self.label_DEM_data_4.setText(QCoreApplication.translate("MainWindow", u"max x", None))
        self.label_DEM_data_3.setText(QCoreApplication.translate("MainWindow", u"min x", None))
        self.x_min.setSuffix(QCoreApplication.translate("MainWindow", u"m", None))
        self.btn_lin_prof.setText(QCoreApplication.translate("MainWindow", u"Add linear profile on SLBL", None))
        self.label_DEM_data_5.setText(QCoreApplication.translate("MainWindow", u"ratio left", None))
        self.label_DEM_data_6.setText(QCoreApplication.translate("MainWindow", u"ratio right", None))
        self.r_left.setSuffix("")
        self.r_right.setSuffix("")
        self.vec_axis.setText(QCoreApplication.translate("MainWindow", u"Axis 1:1", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Slide Selection", None))
        self.dv_slbl1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.dv_slbl2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.dv_slbl3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.dv_slbl5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.dv_slbl6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.dv_slbl4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DISP_VEC), QCoreApplication.translate("MainWindow", u"Displacement Vectors", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Process", None))
        self.btn_clear_comp_disp.setText(QCoreApplication.translate("MainWindow", u"Clear graph", None))
        self.btn_save_comp_disp.setText(QCoreApplication.translate("MainWindow", u"Save Model", None))
        self.btn_graph_model.setText(QCoreApplication.translate("MainWindow", u"Display Model", None))
        self.btn_load_disp_data.setText(QCoreApplication.translate("MainWindow", u"Load Displacement Data", None))
        self.btn_compute_model.setText(QCoreApplication.translate("MainWindow", u"Compute Model", None))
        self.btn_graph_comp.setText(QCoreApplication.translate("MainWindow", u"Display Difference", None))
        self.btn_def_model.setText(QCoreApplication.translate("MainWindow", u"Compute deformable model", None))
        self.btn_graph_corr.setText(QCoreApplication.translate("MainWindow", u"Display Correlation", None))
        self.model_axis.setText(QCoreApplication.translate("MainWindow", u"Axis 1:1", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Slide Selection and Coefficient", None))
        self.dm_slbl1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.dm_slbl2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.dm_slbl3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.dm_slbl5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.dm_slbl6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.dm_slbl4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.COMP_DISP), QCoreApplication.translate("MainWindow", u"Displacement Model", None))
    # retranslateUi

