# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form_slbl.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDoubleSpinBox, QFrame, QLabel,
    QPushButton, QSizePolicy, QSpinBox, QTabWidget,
    QWidget)

class Ui_Form(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Compute_SLBL):
        if not Compute_SLBL.objectName():
            Compute_SLBL.setObjectName(u"Compute_SLBL")
        Compute_SLBL.resize(300, 400)
        font = QFont()
        font.setFamilies([u"Bahnschrift"])
        font.setPointSize(12)
        Compute_SLBL.setFont(font)
        self.label_title = QLabel(Compute_SLBL)
        self.label_title.setObjectName(u"label_title")
        self.label_title.setGeometry(QRect(120, 0, 101, 61))
        font1 = QFont()
        font1.setFamilies([u"Bahnschrift SemiBold Condensed"])
        font1.setPointSize(24)
        font1.setBold(True)
        self.label_title.setFont(font1)
        self.box_tol = QDoubleSpinBox(Compute_SLBL)
        self.box_tol.setObjectName(u"box_tol")
        self.box_tol.setGeometry(QRect(140, 130, 71, 31))
        self.box_tol.setDecimals(4)
        self.box_tol.setMinimum(0.000100000000000)
        self.box_tol.setMaximum(9.999000000000001)
        self.box_tol.setSingleStep(0.010000000000000)
        self.box_tol.setValue(2.000000000000000)
        self.box_left_lim = QDoubleSpinBox(Compute_SLBL)
        self.box_left_lim.setObjectName(u"box_left_lim")
        self.box_left_lim.setGeometry(QRect(140, 50, 71, 31))
        self.box_left_lim.setDecimals(1)
        self.box_left_lim.setMaximum(50000.000000000000000)
        self.box_left_lim.setValue(100.000000000000000)
        self.label_right_lim = QLabel(Compute_SLBL)
        self.label_right_lim.setObjectName(u"label_right_lim")
        self.label_right_lim.setGeometry(QRect(30, 90, 101, 41))
        self.label_tolerance = QLabel(Compute_SLBL)
        self.label_tolerance.setObjectName(u"label_tolerance")
        self.label_tolerance.setGeometry(QRect(30, 130, 91, 41))
        self.box_right_lim = QDoubleSpinBox(Compute_SLBL)
        self.box_right_lim.setObjectName(u"box_right_lim")
        self.box_right_lim.setGeometry(QRect(140, 90, 71, 31))
        self.box_right_lim.setDecimals(1)
        self.box_right_lim.setMaximum(50000.000000000000000)
        self.box_right_lim.setValue(500.000000000000000)
        self.label_left_lim = QLabel(Compute_SLBL)
        self.label_left_lim.setObjectName(u"label_left_lim")
        self.label_left_lim.setGeometry(QRect(30, 50, 91, 41))
        self.line = QFrame(Compute_SLBL)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(60, 190, 201, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.tabWidget = QTabWidget(Compute_SLBL)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 230, 301, 171))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.btn_C_range = QPushButton(self.tab)
        self.btn_C_range.setObjectName(u"btn_C_range")
        self.btn_C_range.setGeometry(QRect(70, 80, 151, 51))
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.spinBox_comb2 = QSpinBox(self.tab_3)
        self.spinBox_comb2.setObjectName(u"spinBox_comb2")
        self.spinBox_comb2.setGeometry(QRect(170, 20, 51, 31))
        self.spinBox_comb2.setMinimum(1)
        self.spinBox_comb2.setMaximum(6)
        self.label_4 = QLabel(self.tab_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 30, 81, 21))
        self.spinBox_comb1 = QSpinBox(self.tab_3)
        self.spinBox_comb1.setObjectName(u"spinBox_comb1")
        self.spinBox_comb1.setGeometry(QRect(90, 21, 51, 31))
        self.spinBox_comb1.setMinimum(1)
        self.spinBox_comb1.setMaximum(6)
        self.btn_C_combined = QPushButton(self.tab_3)
        self.btn_C_combined.setObjectName(u"btn_C_combined")
        self.btn_C_combined.setGeometry(QRect(70, 80, 151, 51))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.btn_C_sub = QPushButton(self.tab_2)
        self.btn_C_sub.setObjectName(u"btn_C_sub")
        self.btn_C_sub.setGeometry(QRect(70, 80, 151, 51))
        self.spinBox_master = QSpinBox(self.tab_2)
        self.spinBox_master.setObjectName(u"spinBox_master")
        self.spinBox_master.setGeometry(QRect(170, 30, 51, 31))
        self.spinBox_master.setMinimum(1)
        self.spinBox_master.setMaximum(6)
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 20, 111, 41))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.btn_C_point = QPushButton(self.tab_4)
        self.btn_C_point.setObjectName(u"btn_C_point")
        self.btn_C_point.setGeometry(QRect(70, 90, 151, 51))
        self.label = QLabel(self.tab_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 0, 91, 41))
        self.label_2 = QLabel(self.tab_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 91, 41))
        self.x1 = QDoubleSpinBox(self.tab_4)
        self.x1.setObjectName(u"x1")
        self.x1.setGeometry(QRect(100, 10, 81, 31))
        self.x1.setDecimals(0)
        self.x1.setMinimum(-99999.000000000000000)
        self.x1.setMaximum(99999.000000000000000)
        self.z1 = QDoubleSpinBox(self.tab_4)
        self.z1.setObjectName(u"z1")
        self.z1.setGeometry(QRect(200, 10, 81, 31))
        self.z1.setDecimals(0)
        self.z1.setMinimum(-99999.000000000000000)
        self.z1.setMaximum(99999.000000000000000)
        self.x2 = QDoubleSpinBox(self.tab_4)
        self.x2.setObjectName(u"x2")
        self.x2.setGeometry(QRect(100, 50, 81, 31))
        self.x2.setDecimals(0)
        self.x2.setMinimum(-99999.000000000000000)
        self.x2.setMaximum(99999.000000000000000)
        self.z2 = QDoubleSpinBox(self.tab_4)
        self.z2.setObjectName(u"z2")
        self.z2.setGeometry(QRect(200, 50, 81, 31))
        self.z2.setDecimals(0)
        self.z2.setMinimum(-99999.000000000000000)
        self.z2.setMaximum(99999.000000000000000)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Compute_SLBL)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Compute_SLBL)
    # setupUi

    def retranslateUi(self, Compute_SLBL):
        Compute_SLBL.setWindowTitle(QCoreApplication.translate("Compute_SLBL", u"Form", None))
        self.label_title.setText(QCoreApplication.translate("Compute_SLBL", u"SLBL", None))
        self.box_left_lim.setSuffix(QCoreApplication.translate("Compute_SLBL", u"m", None))
        self.label_right_lim.setText(QCoreApplication.translate("Compute_SLBL", u"Right limit", None))
        self.label_tolerance.setText(QCoreApplication.translate("Compute_SLBL", u"Tolerance", None))
        self.box_right_lim.setSuffix(QCoreApplication.translate("Compute_SLBL", u"m", None))
        self.label_left_lim.setText(QCoreApplication.translate("Compute_SLBL", u"Left limit", None))
        self.btn_C_range.setText(QCoreApplication.translate("Compute_SLBL", u"Compute", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Compute_SLBL", u"Range", None))
        self.label_4.setText(QCoreApplication.translate("Compute_SLBL", u"SLBLs:", None))
        self.btn_C_combined.setText(QCoreApplication.translate("Compute_SLBL", u"Compute", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Compute_SLBL", u"Combine", None))
        self.btn_C_sub.setText(QCoreApplication.translate("Compute_SLBL", u"Compute", None))
        self.label_6.setText(QCoreApplication.translate("Compute_SLBL", u"Master SLBL:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Compute_SLBL", u"Sub", None))
        self.btn_C_point.setText(QCoreApplication.translate("Compute_SLBL", u"Compute", None))
        self.label.setText(QCoreApplication.translate("Compute_SLBL", u"Point left", None))
        self.label_2.setText(QCoreApplication.translate("Compute_SLBL", u"Point right", None))
        self.x1.setPrefix(QCoreApplication.translate("Compute_SLBL", u"x:  ", None))
        self.x1.setSuffix(QCoreApplication.translate("Compute_SLBL", u"m", None))
        self.z1.setPrefix(QCoreApplication.translate("Compute_SLBL", u"z:  ", None))
        self.z1.setSuffix(QCoreApplication.translate("Compute_SLBL", u"m", None))
        self.x2.setPrefix(QCoreApplication.translate("Compute_SLBL", u"x:  ", None))
        self.x2.setSuffix(QCoreApplication.translate("Compute_SLBL", u"m", None))
        self.z2.setPrefix(QCoreApplication.translate("Compute_SLBL", u"z:  ", None))
        self.z2.setSuffix(QCoreApplication.translate("Compute_SLBL", u"m", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Compute_SLBL", u"Point", None))
    # retranslateUi

